server:
  port: 8080
  servlet:
    context-path: /springbucks

spring:
  datasource:
    username: springbucks
    password: 123
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml